name: Pytests and docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    
    - uses: goanpeca/setup-miniconda@v1
      with:
          activate-environment: ci_env
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false  

    - name: Install scikit-clean from source
      shell: bash -l {0}
      run: pip install --no-deps -e .

    - name: View hardware & software info
      shell: bash -l {0}
      run: |
        python -V
        conda -V
        python -c "import multiprocessing as mp; print('CPU:',mp.cpu_count())"
        python -c "import sklearn;print(sklearn.show_versions())"

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest
        
    - name: Test docs
      shell: bash -l {0}
      run: |
        cd doc
        make html

    - name: Test package building
      shell: bash -l {0}
      run: |
        pip install --upgrade setuptools wheel
        python setup.py sdist bdist_wheel